name: Tests

on: push

env:
  REGISTRY_PERSISTENCE_DIR: "test_registry_persistence_dir"
  REGISTRY_ID: "test_id"


jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        echo $REGISTRY_PERSISTENCE_DIR
        echo $REGISTRY_ID
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: "0.7.21"
    - name: "Set up Python"
      uses: actions/setup-python@v5
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 8.0
    - name: Install Dependencies
      run: |
        cd backend
        uv sync --locked --all-extras --dev
    - name: Run package Tests
      run: |
        cd backend
        uv run pytest
    - name: Run API Tests
      run: |
        cd backend
        uv run manage.py test --exclude-tag=slow
    - name: Run Slow API Tests (main branch only)
      if: github.ref == 'refs/heads/main'
      run: |
        cd backend
        uv run manage.py test --tag=slow

